version: '3.3'

services:
  postgresql:
    image: postgres:15
    volumes:
      - postgres_vol:/var/lib/postgresql15/data/
    environment:
      - POSTGRES_PASSWORD=adminpostgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=RheemCSmessages
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

  telebot:
     build:
       context: .
       dockerfile: ./Dockerfile
     command: >
       sh -c "python main.py"
     volumes:
       - .:/usr/src
     ports:
       - "8001:8000"
     depends_on:
       postgresql:
         condition: service_healthy

  endpoint:
    build:
       context: .
       dockerfile: ./Dockerfile
    command: >
      uvicorn endpoint:app --port 8000 --host 0.0.0.0 --reload
    volumes:
      - .:/usr/src
    ports:
      - "8000:8000"

volumes:
  postgres_vol:
